### ISSUE TITLE
画像保存機能

### ISSUE THREAD

**Issue by grfsv** [kimetaato/streview-sv#1]
## 概要
multipart/form-dataから受け取った画像の保存を行うアプリケーションサービスを追加
ストレージ容量削減のため、webpに変換して保存する。

## 解決策
アプリケーション層でインターフェースとして画像保存を行うサービスを定義し、インフラストラクチャ層で実装を行う。

application.yamlで用途ごとの保存先の指定を行う。
``` 
app:
  storage:
    images:
      user_icon: #アイコン画像の保存先
      review: #レビュー画像の保存先
      store: #店舗画像の保存先
```

**使用ライブラリ**
- rkalla / imgscalr
- TwelveMonkeys / ImageIO

## 代替案

Ktorフレームワークの標準機能を利用して画像の保存を行う。
責務の分離の観点から解決策を選択。

## 補足事項
画像取得は同一サービス内に署名つきURLを発行する関数を実装して行う予定。
